"""
YantraRakshak MPU (Qualcomm Linux) side configuration.

Wi-Fi itself is configured at the Debian OS level (nmcli / the UNO Q's
network settings), not here -- confirmed via
docs.arduino.cc + kevsrobots.com/blog/arduino-uno-q-wifi-setup.html, Wi-Fi
on this board is owned by the Linux side's own network stack. This file
only configures what our Python brick needs on top of that: MQTT broker
details, the machine identity, and inference thresholds.
"""

MACHINE_ID = "Lathe-01"  # must match sketch/src/config/Config.h::MachineConfig::kMachineId

MQTT_BROKER_HOST = "192.168.1.50"  # Windows laptop's LAN IP
MQTT_BROKER_PORT = 1883
MQTT_CLIENT_ID = f"yantra-rakshak-{MACHINE_ID}"
MQTT_KEEPALIVE_SECONDS = 60

MQTT_TOPIC_PREFIX = f"plant/{MACHINE_ID}"
MQTT_TELEMETRY_TOPIC = f"{MQTT_TOPIC_PREFIX}/telemetry"
MQTT_ALERT_TOPIC = f"{MQTT_TOPIC_PREFIX}/alert"
MQTT_STATUS_TOPIC = f"{MQTT_TOPIC_PREFIX}/status"

MQTT_STATUS_ONLINE_PAYLOAD = "online"
MQTT_STATUS_OFFLINE_PAYLOAD = "offline"

HEARTBEAT_INTERVAL_SECONDS = 30

# Model + calibration -- generated by
# machine-learning/training/train_autoencoder.py from real CWRU Bearing
# Data Center recordings. See docs/MODEL_TRAINING_REPORT.md.
MODEL_PATH = "model/autoencoder_int8.tflite"
FEATURE_COUNT = 5
FEATURE_NAMES = ["mean", "rms", "peak", "crest_factor", "kurtosis"]
WARNING_THRESHOLD = 1.777191
CRITICAL_THRESHOLD = 2.914409
