#ifndef YANTRA_RAKSHAK_MODEL_DATA_H
#define YANTRA_RAKSHAK_MODEL_DATA_H

// The INT8-quantized vibration-anomaly autoencoder, trained on real CWRU
// Bearing Data Center recordings by
// machine-learning/training/train_autoencoder.py (see
// docs/MODEL_TRAINING_REPORT.md for methodology, data sources, and
// results). This header only declares the symbols; the actual trained
// bytes live in model_data.cpp and must be regenerated by re-running that
// script if the model is retrained -- never hand-edited.
extern const unsigned char g_model[];
extern const unsigned int g_model_len;

#endif // YANTRA_RAKSHAK_MODEL_DATA_H
